AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "libs/platforms/config.rb"
