AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false
