name: RSpec

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Ruby (3.2)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Build and test with RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
