name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ["3.4.2"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run tests
        run: bundle exec rake

      - name: Ensure coverage file exists
        run: ls -la coverage

      - name: Rename coverage file
        run: mv coverage/Interactsh-Library.lcov coverage/lcov.info
        if: success()

      - name: Publish code coverage
        run: |
          ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}} -t lcov
        if: success()
